FROM quay.io/centos/centos:stream9

# Basic packages
RUN dnf install -y \
      bash \
      git \
      jq \
      sudo

# Foreman packages
RUN dnf install -y https://yum.puppet.com/puppet8-release-el-9.noarch.rpm && \
    dnf install -y https://yum.theforeman.org/releases/3.16/el9/x86_64/foreman-release.rpm && \
    dnf install -y foreman-installer && \
    dnf clean all

RUN useradd coder \
    --create-home \
    --shell=/bin/bash \
    --uid=1000 \
    --user-group && \
    echo "coder ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers.d/nopasswd

USER coder